mode: MPIIFaceGaze
device: cuda
dataset:
  dataset_dir: output/MPIIFaceGaze.h5
transform:
  mpiifacegaze_face_size: 224
  mpiifacegaze_gray: False
model:
  name: resnet_simple_muti
  backbone:
    name: resnet_simple
    pretrained: resnet18
    resnet_block: basic
    resnet_layers: [2, 2, 2]
train:
  batch_size: 32
  optimizer: adamHeadP
  base_lr: 0.1
  momentum: 0.9
  nesterov: True
  weight_decay: 0.0001
  no_weight_decay_on_bn: False
  loss: L1
  seed: 0
  test_id: 0
  val_ratio: 0.1
  output_dir: experiments/mpiifacegaze/resnet_simple_muti/exp00
  log_period: 100
  checkpoint_period: 5
  use_tensorboard: True
  # 添加多任务损失权重，给 Pose 分配更大的权重
  gaze_loss_weight: 1.0
  pose_loss_weight: 4.0
  train_dataloader:
    num_workers: 0
    drop_last: True
    pin_memory: False
  val_dataloader:
    num_workers: 0
    pin_memory: False
scheduler:
  epochs: 30
  type: multistep
  milestones: [10, 13]
  lr_decay: 0.1
  lr_min_factor: 0.001
cudnn:
  benchmark: True
  deterministic: False
